### ISSUE TITLE
how to  show the open simulation tab 

### ISSUE THREAD

**Issue by ZeacenLee** [robidev/iec61850_open_server#4]
1. I cannot show "modify" button
2. I cannot see "status" information
3. 
![image](https://user-images.githubusercontent.com/52440833/143870759-c3920dfa-4fe0-47e9-85d1-b1b3b556532a.png)

**Comment by ZeacenLee** [comment]
This is the client via the browser
![image](https://user-images.githubusercontent.com/52440833/143871253-c1c9601f-0a74-4e94-80b3-dede7ba97735.png)

**Comment by robidev** [comment]
Thank you for raising this issue. It is curious, as it does not seem to happen on my machine.. It seems the browser for the simulation-tab cannot access the backend, as 'status:' should show init:ok, Would you be able to verify, what your browser says, when you open the debugger-panel of the simulation tab?

Additionally, can you see if the iec61850_open_server_simulator_1 is running, and if any error is displayed in the logs?

I have updated the debian image used, and upgraded eventled and flask. Perhaps this will solve your issue as well

**Comment by robidev** [comment]
Additionally, can you see if the iec61850_open_server_simulator_1 is running, and if any error is displayed in the logs?

**Comment by ZeacenLee** [comment]
First of all, I am honored to get your reply, I am solving the comments you gave, your project is very helpful to my research work, I am also studying the libiec61850 simulation of intelligent substation, I hope to continue to keep communication with you

**Comment by robidev** [comment]
Sure, feel free to reach me directly on robin.dev[at]gmail.com

**Comment by ZeacenLee** [comment]
Robidev,I'm so happy! I solved my problem. Because I come from China, there are some restrictions on introducing some Google APIs. I changed the API to solve this problem.
![image](https://user-images.githubusercontent.com/52440833/145052296-cbd7777d-5f3d-48d1-902b-fbb2a5be8f85.png)

**Comment by ZeacenLee** [comment]
![image](https://user-images.githubusercontent.com/52440833/145052515-22b0a278-cbc7-48da-9a3d-a0f7168dfd77.png)

**Comment by ZeacenLee** [comment]
In addition, I found that without MMS, can we improve this project together?

**Comment by robidev** [comment]
I'm happy to hear you found the issue. However, I'm not sure if this can be permanently be resolved. A small workaround would be to disable internet when starting the browser, to ensure jquery is loaded locally. (it should trigger the if(typedef jQuery == 'undefined') ).

In addition, I'm not sure what you mean with _"I found that without MMS"_ The project uses MMS for client-server communication, and GOOSE+SMV9-2 for communication between IED's. But if you have suggestions for improvement, feel free to provide them via pull-request.
