### ISSUE TITLE
Operation via external IEC 61850 Client

### ISSUE THREAD

**Issue by hometm** [robidev/iec61850_open_server#5]
Is it possible to operate the switchgear via an other IEC 61850 client via the network?

**Comment by robidev** [comment]
yes, that should be no problem. Therefore you have 3 options that docker-compose provides; 

1 you should bridge the docker-network with a real network, where your IEC 61850 client resides.  ( https://docs.docker.com/network/bridge/ )

2. Alernatively, include the IEC 61850 client in the docker-compose-file. ( https://docs.docker.com/compose/gettingstarted/ )

3. or you need to expose the ports of the IEC-61850 servers to the host, and run the IEC 61850 client there, and connect to the exposed port on localhost. ( https://docs.docker.com/compose/networking/ )

All of these are not features regarding this specific project, but a result of using docker-compose for the network.

**Comment by hometm** [comment]
From other PC in the network, I can reach the web server on port 5000. But if I try to connect via IEC browser on default port 102, it is not able to connect to the IEC Server. I'm using this IEC browser https://support.industry.siemens.com/cs/document/109744534/sicam-iec-browser?dti=0&lc=en-WW

**Comment by robidev** [comment]
That is correct. As you can see in the docker-compose file, port 5000 of the client is exposed to the host, but port 102 of any of the 4 servers running is not. (within the docker-compose network, there are in total 6 servers running; 4 IED servers, 1 client and a simulator) If you want to connect to 1 of those 4 IED's that run within docker-compose with your sicam IEC-browser, you need to expose the 102 port of 1 of the servers to your host(like i described in step 3 of my previous answer). It seems to me from your question, you're not familiar with docker(-compose). I suggest you read a bit into it if you want to use/modify this  docker-compose setup. (https://docs.docker.com/compose/)

You could also run a server directly on your host, by manually compiling IEC61850-server, providing it a config, and starting it. 
Building the project means you first build libiec61850, and install it, and then do a 
`$ cmake .`
 and then 
`$ make`
provided you have all dependencies, such as build-essential and cmake  (` $ sudo apt install build-essential cmake`)
An example of commands to start a server locally are described into https://github.com/robidev/iec61850_open_server/blob/master/local_test.sh. But be aware you can only start one server on port 102, so you have to modify that file to define the server you want to have listen on port 102. i.e. ./open_server lo 102 cfg/IED1_XCBR.cfg cfg/IED1_XCBR.ext L 65000 will start a server listening on localhost, port 102, and no simulator attached.

**Comment by hometm** [comment]
Many thanks!
