### ISSUE TITLE
SCD Instantiation 

### ISSUE THREAD

**Issue by MFowler9** [robidev/iec61850_open_server#9]
Hi folks, after following the "easiest way to get started" portion of the read me I seem to only be getting the Substation Circuit Simulator and no HMI or IED interfaces. Reading through the XML of the .scd file shows that all classes and references are set in there but I cannot seem to get these representations to show themselves. Due to the lack of issues mentioned here I assume that this is an error on the user-end of this equation. But I was hoping to ask for some guidance on how to achieve the GUI as displayed in the example screenshot. Hope to hear back from yall.

Thanks for making this project.

**Comment by robidev** [comment]
Hi, Could you post a screenshot of what you mean by only getting the substation circuit simulator? You should be opening 127.0.0.1:5000, which should include the HMI. The substation circuit simulator is listening on 127.0.0.1:5010 instead. Additionally, did you check if the correct containers are running? using `docker ps` you should see the following containers instantiated and running; IED 1, IED 2, IED 3, IED 4, client, simulator. So 6 in total. Perhaps the client container failed to start? Additionally, you could check using `netstat -tulpn` or `ss -ltpn`. Best regards,

Robin

**Comment by MFowler9** [comment]
Sure enough:

This is what is displayed in the shell window
https://imgur.com/Iz87wXE

This is when accessing 127.0.0.1:5000
https://imgur.com/amQsPHF

And when accessing 127.0.0.1:5010
https://imgur.com/KjeoDV2

When checking docker ps it reveals the client container is indeed failing to start. What would the correct command string be to properly set that up?
https://imgur.com/UQV8dep

Thanks for the assistance,

Myles

**Comment by robidev** [comment]
Great, your first screenshot actually displays the issue; the dns.rdtypes has no attribute ANY error is causing the client not to start. This was fixed 2 weeks ago, but I think you were a bit unlucky and cloned the repo just before that. 

Bumping eventlet to version 0.33.3 for the client seems to fix this. Ive updated the repo(so do a clean clone of both server and client project like you did before), or you can modify requirements.txt yourself manually; eventlet==0.33.2 -> eventlet==0.33.3.

After modifying, you will need to rebuild the container. i.e.

$ sudo docker-compose -f substation.yml -f substation.simulator.yml build

that should solve your issue hopefully.

Please let me know if it did.

Best regards,

Robin

**Comment by MFowler9** [comment]
What timing haha, I'll follow your advice and respond back!

**Comment by MFowler9** [comment]
Got everything up and running by blowing away the old directory and starting fresh. Thanks for the advice Robin!

**Comment by robidev** [comment]
this issue can be closed now
